CREATE TABLE New_Deck(

	Deck_ID VARCHAR(15) NOT NULL,
	Player_ID VARCHAR(15) NOT NULL,
	d_name VARCHAR(50) NOT NULL

);

CREATE TABLE Deck_Card(

	Deck_ID VARCHAR(15) NOT NULL,
	Card_ID VARCHAR(15) NOT NULL

);

ALTER TABLE New_Deck
ADD CONSTRAINT PK_Decks
PRIMARY KEY (Deck_ID);

ALTER TABLE New_Deck
ADD CONSTRAINT UC_DeckName UNIQUE (Deck_ID,Player_ID);

ALTER TABLE New_Deck
ADD CONSTRAINT FK_Decks
FOREIGN KEY (Player_ID) REFERENCES Users(ID);

ALTER TABLE Deck_Card
ADD CONSTRAINT FK_Card_DeckID
FOREIGN KEY (Deck_ID) REFERENCES New_Deck(Deck_ID);

ALTER TABLE Deck_Card
ADD CONSTRAINT FK_CardID_Deck
FOREIGN KEY (Card_ID) REFERENCES Cards(ID);

ALTER TABLE Deck_Card
ADD CONSTRAINT PK_DeckCard
PRIMARY KEY (Deck_ID,Card_ID)