DROP TABLE IF EXISTS Planet;
DROP TABLE IF EXISTS Partida;
DROP TABLE IF EXISTS New_Deck;
DROP TABLE IF EXISTS Deck_Card;
DROP TABLE IF EXISTS User_card;
DROP TABLE IF EXISTS Cards;
DROP TABLE IF EXISTS Race;
DROP TABLE IF EXISTS Users;