CREATE TABLE Partida(
	ID VARCHAR(15) NOT NULL,
	Player1 VARCHAR(15),
	Player2 VARCHAR(15),
	Winner VARCHAR(15),
	Planet1 VARCHAR(15),
	Planet2 VARCHAR(15),
	Planet3 VARCHAR(15),
	p_status VARCHAR(30), --En curso: EC, T: Terminada
	C_Turn VARCHAR(15), --Current turn
	TurnCount INT
);

ALTER TABLE Partida
ADD CONSTRAINT FK_P1
FOREIGN KEY (Player1) REFERENCES Users(ID);

ALTER TABLE Partida
ADD CONSTRAINT FK_P2
FOREIGN KEY (Player2) REFERENCES Users(ID);

ALTER TABLE Partida
ADD CONSTRAINT FK_WIN
FOREIGN KEY (Winner) REFERENCES Users(ID);

ALTER TABLE Partida
ADD CONSTRAINT FK_PLANET1
FOREIGN KEY (Planet1) REFERENCES Planet(ID);

ALTER TABLE Partida
ADD CONSTRAINT FK_PLANET2
FOREIGN KEY (Planet2) REFERENCES Planet(ID);

ALTER TABLE Partida
ADD CONSTRAINT FK_PLANET3
FOREIGN KEY (Planet3) REFERENCES Planet(ID);

ALTER TABLE Partida
ADD CONSTRAINT PK_PartidaID
PRIMARY KEY (ID);
